server:
  port: 8082

spring:
  application:
    name: course-management-service

  datasource:
    url: jdbc:mysql://localhost:3306/course_management_db?createDatabaseIfNotExist=true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    # properties:
    #   hibernate:
    #     format_sql: true

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true   # ✅ Added for Feign fallback
    
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
        fetch-registry: true
        register-with-eureka: true
      instance:
        prefer-ip-address: true