server:
  port: 8082

spring:
  application:
    name: course-management-service

  datasource:
    url: jdbc:mysql://localhost:3306/course_management_db?createDatabaseIfNotExist=true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
